python main.py \
  method=poison_files \
  model.pretrained=false \
  dataset=flare21 \
  task.run_name=victim_random_noise_gaussian_4_255 \
  model=unet \
  model.name=unet \
  task=flare21_seg \
  training.epochs=100 \
  training.optimizer=adam \
  training.optimizers.adam.lr=5e-4 \
  training.gpu_ids=[7] \
  training.batch_size=8 \
  training.eval_batch_size=8 \
  training.data.poison.enabled=true \
  training.data.poison.perturb_type=samplewise \
  training.data.poison.key.type=samplewise \
  training.data.poison.key.from=field \
  training.data.poison.key.field=case_id \
  training.data.poison.source.type=manifest \
  training.data.poison.source.manifest_path=/home/dengzhipeng/data/project/3d_ue/outputs/flare21_ue/random_noise_gaussian/20260225_081059/noise/manifest.json &

python main.py \
  method=poison_files \
  model.pretrained=false \
  dataset=brats19 \
  task.run_name=victim_lsp_4_255 \
  model=unet \
  model.name=unet \
  task=brats19_seg \
  training.epochs=100 \
  training.optimizer=adam \
  training.optimizers.adam.lr=5e-4 \
  training.gpu_ids=[7] \
  training.batch_size=8 \
  training.eval_batch_size=8 \
  training.data.poison.enabled=true \
  training.data.poison.perturb_type=samplewise \
  training.data.poison.key.type=samplewise \
  training.data.poison.key.from=field \
  training.data.poison.key.field=case_id \
  training.data.poison.source.type=manifest \
  training.data.poison.source.manifest_path=/home/dengzhipeng/data/project/3d_ue/outputs/brats19_ue/lsp_noise_4_255/20260225_074314/ue/lsp/manifest.json
