# file: src/core/ue_algos/coherent_spectral_ue.py
"""
Coherent Spectral UE with learnable spectral parameters.

Core idea:
  - Learn a spectral tensor P (complex: real + imag) directly in frequency domain
  - Apply fixed spectral mask M to constrain frequency support
  - Apply inverse FFT to get spatial perturbation: delta = IFFT(M * P)
  - Apply ROI spatial gating with Gaussian smoothing

Key difference from UNet-based methods:
  - P is learned directly in frequency domain (not generated by UNet)
  - P is global per sample/class (not image-dependent)
  - Enforces spectral coherence by design (z-axis low-freq + xy-plane band-pass)
"""
from __future__ import annotations
from typing import Any, Dict, Iterable, List, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from omegaconf import DictConfig
from monai.losses import DiceCELoss

from ...registry import register_plugin
from ...utils.config import get_config, require_config
from ...utils.logger import get_logger


def _gaussian_kernel_3d(sigma: float, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
    """
    Create a 3D Gaussian kernel for smoothing.

    Args:
        sigma: Standard deviation for Gaussian
        device: torch device
        dtype: torch dtype

    Returns:
        kernel: [1, 1, K, K, K] Gaussian kernel
    """
    if sigma <= 0:
        raise ValueError("sigma must be > 0 for gaussian kernel.")

    radius = int(round(2.0 * sigma))
    coords = torch.arange(-radius, radius + 1, device=device, dtype=dtype)
    g = torch.exp(-(coords**2) / (2 * sigma**2))
    g = g / g.sum()

    kernel_1d = g.view(1, 1, -1)
    kernel_3d = (
        kernel_1d[:, :, :, None, None]
        * kernel_1d[:, :, None, :, None]
        * kernel_1d[:, :, None, None, :]
    )
    return kernel_3d


class SpectralPerturbationField(nn.Module):
    """
    Learnable spectral perturbation field with frequency-domain mask.

    Parameters:
        - P_real, P_imag: [C, D, H, W] learnable complex spectral parameters
        - M: [1, D, H, W] fixed frequency mask (not learnable)

    Forward:
        delta = IFFT(M * (P_real + i*P_imag))
    """

    def __init__(
        self,
        C: int,
        D: int,
        H: int,
        W: int,
        spectral_mask_config: DictConfig,
        device: torch.device,
        dtype: torch.dtype = torch.float32,
    ):
        super().__init__()
        self.C = C
        self.D = D
        self.H = H
        self.W = W

        # Learnable spectral parameters (real + imaginary)
        init_scale = float(get_config(spectral_mask_config, "init_scale", 0.01))
        self.P_real = nn.Parameter(torch.randn(C, D, H, W, dtype=dtype, device=device) * init_scale)
        self.P_imag = nn.Parameter(torch.randn(C, D, H, W, dtype=dtype, device=device) * init_scale)

        # Fixed frequency mask
        M = self._build_spectral_mask(D, H, W, spectral_mask_config, device, dtype)
        self.register_buffer("M", M)

    @staticmethod
    def _build_spectral_mask(
        D: int,
        H: int,
        W: int,
        cfg: DictConfig,
        device: torch.device,
        dtype: torch.dtype,
    ) -> torch.Tensor:
        """
        Build 3D frequency-domain mask [1, D, H, W].

        Constraints:
          - Z-axis (slice direction): low-frequency only (|f_z| <= z_max)
          - XY-plane (in-plane): band-pass (xy_min <= |f_xy| <= xy_max)
        """
        z_max = float(get_config(cfg, "z_max", 0.125))
        xy_min = float(get_config(cfg, "xy_min", 0.05))
        xy_max = float(get_config(cfg, "xy_max", 0.3))

        # Build frequency grids
        fz = torch.fft.fftfreq(D, device=device, dtype=dtype).abs()  # [D]
        fy = torch.fft.fftfreq(H, device=device, dtype=dtype).abs()  # [H]
        fx = torch.fft.fftfreq(W, device=device, dtype=dtype).abs()  # [W]

        # Create 3D meshgrid
        zz, yy, xx = torch.meshgrid(fz, fy, fx, indexing="ij")  # [D, H, W]

        # Z-axis constraint: low-frequency
        mask_z = (zz <= z_max)

        # XY-plane constraint: band-pass (radial frequency)
        fxy = torch.sqrt(yy**2 + xx**2)
        mask_xy = (fxy >= xy_min) & (fxy <= xy_max)

        # Combine constraints
        mask = (mask_z & mask_xy).to(dtype=dtype)

        return mask.unsqueeze(0)  # [1, D, H, W]

    def forward(self) -> torch.Tensor:
        """
        Generate spatial perturbation from learnable spectral parameters.

        Returns:
            delta: [C, D, H, W] spatial perturbation
        """
        # Construct complex spectral tensor
        P_complex = torch.complex(self.P_real, self.P_imag)  # [C, D, H, W]

        # Apply frequency mask
        P_masked = P_complex * self.M  # [C, D, H, W] * [1, D, H, W]

        # Inverse FFT to spatial domain
        delta = torch.fft.ifftn(P_masked, dim=(-3, -2, -1)).real  # [C, D, H, W]

        return delta


class ROISpatialGate(nn.Module):
    """
    ROI spatial gate with Gaussian-smoothed edges.

    Args:
        roi_config: ROI gating configuration
    """

    def __init__(self, roi_config: DictConfig):
        super().__init__()
        self.dilate_kernel_size = int(get_config(roi_config, "dilate_kernel_size", 3))
        self.gaussian_sigma = float(get_config(roi_config, "gaussian_sigma", 2.0))

    def forward(self, label: torch.Tensor) -> torch.Tensor:
        """
        Generate smooth ROI mask from segmentation label.

        Args:
            label: [B, D, H, W] or [B, 1, D, H, W] segmentation label

        Returns:
            roi_mask: [B, 1, D, H, W] smooth ROI mask in [0, 1]
        """
        # Ensure label is [B, D, H, W]
        if label.dim() == 5:
            label = label.squeeze(1)

        # Create binary mask: ROI = label > 0
        mask = (label > 0).float()  # [B, D, H, W]

        # Optional: Morphological dilation
        if self.dilate_kernel_size > 0:
            mask_unsqueezed = mask.unsqueeze(1)  # [B, 1, D, H, W]
            kernel_size = self.dilate_kernel_size
            padding = kernel_size // 2
            mask = F.max_pool3d(
                mask_unsqueezed,
                kernel_size=kernel_size,
                stride=1,
                padding=padding,
            ).squeeze(1)

        # Add channel dimension: [B, 1, D, H, W]
        mask = mask.unsqueeze(1)

        # Gaussian smoothing for soft edges
        if self.gaussian_sigma > 0:
            kernel = _gaussian_kernel_3d(
                self.gaussian_sigma, device=mask.device, dtype=mask.dtype
            )
            padding = kernel.shape[-1] // 2
            mask = F.conv3d(mask, kernel, padding=padding)
            mask = mask / mask.max().clamp_min(1e-6)

        return mask


@register_plugin("coherent_spectral_ue")
class CoherentSpectralUE:
    """
    Coherent Spectral UE: Learnable spectral parameters with frequency gating and ROI masking.

    Key differences from UNet-based methods:
      1. Parameters are learned directly in frequency domain (not via UNet)
      2. Each sample/class has its own spectral parameters P
      3. Spectral coherence is enforced by fixed mask M
      4. ROI gating with Gaussian smoothing for artifact-free boundaries

    Training flow:
      - Surrogate-step: Train surrogate with fixed perturbations from backend
      - Noise-step: Update spectral parameters P to maximize surrogate loss

    Configuration:
      ue.algorithm.params:
        epsilon: L_inf bound (e.g., 8/255)
        noise_step: Number of gradient steps per batch
        spectral_mask:
          z_max: Z-axis frequency upper bound (default: 0.125)
          xy_min: XY-plane radial frequency lower bound (default: 0.05)
          xy_max: XY-plane radial frequency upper bound (default: 0.3)
          init_scale: Initial scale for P_real, P_imag (default: 0.01)
        roi_gate:
          enabled: Enable ROI gating (default: true)
          dilate_kernel_size: ROI dilation kernel (default: 3)
          gaussian_sigma: Edge smoothing sigma (default: 2.0)
        optimizer:
          lr: Learning rate (default: 1e-3)
          weight_decay: Weight decay (default: 1e-5)
    """

    def __init__(self):
        self._seg_loss: DiceCELoss | None = None
        self._spectral_fields: Dict[Any, SpectralPerturbationField] = {}
        self._roi_gate: ROISpatialGate | None = None
        self._optimizer: torch.optim.Optimizer | None = None
        self._initialized: bool = False
        self.logger = get_logger()

    @staticmethod
    def _norm_inplace(x: torch.Tensor, mean, std):
        """In-place per-channel normalize."""
        for c, (m, s) in enumerate(zip(mean, std)):
            x[:, c].sub_(float(m)).div_(float(s))
        return x

    def _init_components(self, trainer, image_shape: Tuple[int, int, int, int]):
        """
        Initialize spectral fields and ROI gate (lazy, once).

        Args:
            trainer: UETrainer instance
            image_shape: (C, D, H, W)
        """
        if self._initialized:
            return

        cfg = trainer.config
        device = trainer.device
        C, D, H, W = image_shape

        # Get configuration
        algo = require_config(cfg, "ue.algorithm")
        params = require_config(algo, "params")
        spectral_cfg = get_config(params, "spectral_mask", DictConfig({}))
        roi_cfg = get_config(params, "roi_gate", DictConfig({}))

        # Initialize spectral fields (one per key)
        # We'll create them on-demand in noise_step_batch
        self._spectral_fields = {}
        self._image_shape = image_shape
        self._spectral_cfg = spectral_cfg
        self._device = device

        # Initialize ROI gate
        roi_enabled = bool(get_config(roi_cfg, "enabled", True))
        if roi_enabled:
            self._roi_gate = ROISpatialGate(roi_cfg).to(device)
        else:
            self._roi_gate = None

        # Initialize optimizer (will add parameters as spectral fields are created)
        opt_cfg = get_config(params, "optimizer", DictConfig({}))
        lr = float(get_config(opt_cfg, "lr", 1e-3))
        weight_decay = float(get_config(opt_cfg, "weight_decay", 1e-5))
        betas = tuple(get_config(opt_cfg, "betas", (0.9, 0.999)))

        self._opt_params = {"lr": lr, "weight_decay": weight_decay, "betas": betas}
        self._optimizer = None  # Will be created when first spectral field is added

        self._initialized = True
        self.logger.info(
            f"[CoherentSpectralUE] Initialized: image_shape={image_shape}, "
            f"roi_enabled={roi_enabled}, lr={lr}"
        )

    def _get_or_create_spectral_field(self, key: Any) -> SpectralPerturbationField:
        """Get or create spectral field for a given key."""
        if key not in self._spectral_fields:
            C, D, H, W = self._image_shape
            field = SpectralPerturbationField(
                C, D, H, W, self._spectral_cfg, self._device
            )
            self._spectral_fields[key] = field

            # Add to optimizer
            if self._optimizer is None:
                self._optimizer = torch.optim.Adam(
                    field.parameters(), **self._opt_params
                )
            else:
                # Add new parameters to existing optimizer
                self._optimizer.add_param_group({"params": field.parameters()})

            self.logger.info(f"[CoherentSpectralUE] Created spectral field for key={key}")

        return self._spectral_fields[key]

    def _get_seg_loss(self, trainer) -> DiceCELoss:
        """Build DiceCELoss consistent with SegTrainer configuration."""
        if self._seg_loss is not None:
            return self._seg_loss

        cfg = trainer.config
        crit_cfg = get_config(cfg, "training.criterion", DictConfig({}))
        include_background = bool(get_config(crit_cfg, "include_background", False))
        squared_pred = bool(get_config(crit_cfg, "squared_pred", False))
        jaccard = bool(get_config(crit_cfg, "jaccard", False))
        lambda_dice = float(get_config(crit_cfg, "lambda_dice", 1.0))
        lambda_ce = float(get_config(crit_cfg, "lambda_ce", 1.0))

        self._seg_loss = DiceCELoss(
            include_background=include_background,
            to_onehot_y=True,
            softmax=True,
            squared_pred=squared_pred,
            jaccard=jaccard,
            lambda_dice=lambda_dice,
            lambda_ce=lambda_ce,
            reduction="mean",
        )
        return self._seg_loss

    # ---------------- Surrogate-step: Update surrogate ---------------- #
    def surrogate_step_batch(self, trainer, batch) -> Dict[str, float]:
        """
        Update surrogate parameters only, do not update spectral parameters.
        Uses noise from backend (with spectral + ROI constraints already applied).
        """
        cfg = trainer.config
        device = trainer.device
        nb = trainer.noise_backend
        if nb is None:
            raise RuntimeError("[UE] noise_backend is required.")

        x = batch["image"].to(device).float()
        y = batch["label"]
        y = y.to(device).long() if torch.is_tensor(y) else torch.as_tensor(
            y, device=device, dtype=torch.long
        )
        keys: Iterable[Any] = batch["key"]

        B, C_in = x.shape[:2]
        image_shape = tuple(x.shape[1:])  # (C, D, H, W)

        self._init_components(trainer, image_shape)

        mean = tuple(get_config(cfg, "training.data.transforms.mean", (0.0,) * C_in))
        std = tuple(get_config(cfg, "training.data.transforms.std", (1.0,) * C_in))

        delta = nb.batch_noise(list(keys)).to(device).float()
        if delta.shape[:2] != x.shape[:2]:
            raise RuntimeError(
                f"[UE] noise shape mismatch: noise {tuple(delta.shape)} vs input {tuple(x.shape)}"
            )

        if not trainer.surrogates:
            raise RuntimeError("[UE] No surrogate bound.")
        name, s_model = next(iter(trainer.surrogates.items()))
        opt = trainer.opt_surrogates.get(name, None)
        if opt is None:
            raise RuntimeError(f"[UE] No optimizer for surrogate '{name}'.")

        seg_loss_fn = self._get_seg_loss(trainer)

        s_model.train()
        for p in s_model.parameters():
            p.requires_grad = True

        noisy = (x + delta).clamp(0.0, 1.0)
        xn = noisy.clone()
        self._norm_inplace(xn, mean, std)

        out = s_model(xn)
        logits = out[0] if isinstance(out, (tuple, list)) else out

        loss = seg_loss_fn(logits, y.unsqueeze(1))

        opt.zero_grad(set_to_none=True)
        loss.backward()
        opt.step()

        loss_val = float(loss.detach().cpu())
        return {
            "surrogate_loss": loss_val,
            "loss": loss_val,
        }

    # ---------------- N-step: Update spectral parameters ---------------- #
    def noise_step_batch(self, trainer, batch) -> Dict[str, float]:
        """
        Update spectral parameters P to maximize surrogate loss.

        Process:
          1. For each key, get or create spectral field
          2. Generate delta = IFFT(M * P)
          3. Apply ROI spatial gate: delta = delta * ROI_mask
          4. Clip to epsilon
          5. Forward through frozen surrogate
          6. Compute loss and backprop to update P
          7. Store final noise to backend
        """
        cfg = trainer.config
        device = trainer.device
        nb = trainer.noise_backend
        if nb is None:
            raise RuntimeError("[UE] noise_backend is required.")

        x = batch["image"].to(device).float()
        y = batch["label"]
        y = y.to(device).long() if torch.is_tensor(y) else torch.as_tensor(
            y, device=device, dtype=torch.long
        )
        keys = batch["key"]
        keys_list: List[Any] = list(keys)

        B, C_in = x.shape[:2]
        image_shape = tuple(x.shape[1:])  # (C, D, H, W)

        self._init_components(trainer, image_shape)

        algo = require_config(cfg, "ue.algorithm")
        params = require_config(algo, "params")
        eps = float(get_config(params, "epsilon", 8 / 255.0))
        num_steps = int(get_config(params, "noise_step", 1))

        mean = tuple(get_config(cfg, "training.data.transforms.mean", (0.0,) * C_in))
        std = tuple(get_config(cfg, "training.data.transforms.std", (1.0,) * C_in))

        seg_loss_fn = self._get_seg_loss(trainer)

        # Freeze surrogate
        if not trainer.surrogates:
            raise RuntimeError("[UE] No surrogate bound.")
        _, s_model = next(iter(trainer.surrogates.items()))
        s_model.eval()
        for p in s_model.parameters():
            p.requires_grad = False

        # Get ROI mask (if enabled)
        if self._roi_gate is not None:
            roi_mask = self._roi_gate(y)  # [B, 1, D, H, W]
            roi_mask = roi_mask.expand(-1, C_in, -1, -1, -1)  # [B, C, D, H, W]
        else:
            roi_mask = None

        # Train spectral parameters
        last_loss = torch.tensor(0.0, device=device)

        for step in range(max(1, num_steps)):
            # Generate perturbations for each key in batch
            delta_list = []
            for key in keys_list:
                spectral_field = self._get_or_create_spectral_field(key)
                delta_global = spectral_field()  # [C, D, H, W]
                delta_list.append(delta_global)

            delta = torch.stack(delta_list, dim=0)  # [B, C, D, H, W]

            # Apply ROI gate
            if roi_mask is not None:
                delta = delta * roi_mask

            # Clip to epsilon
            delta = delta.clamp(-eps, eps)

            # Create perturbed image
            perturb_img = (x + delta).clamp(0.0, 1.0)
            xn = perturb_img.clone()
            self._norm_inplace(xn, mean, std)

            # Forward through surrogate
            out = s_model(xn)
            logits = out[0] if isinstance(out, (tuple, list)) else out

            # Compute loss
            loss = seg_loss_fn(logits, y.unsqueeze(1))
            last_loss = loss.detach()

            # Backprop to update spectral parameters
            if self._optimizer is None:
                raise RuntimeError("[UE] Optimizer not initialized.")

            self._optimizer.zero_grad(set_to_none=True)
            loss.backward()
            self._optimizer.step()

        # Store final noise to backend
        with torch.no_grad():
            final_delta_list = []
            for key in keys_list:
                spectral_field = self._get_or_create_spectral_field(key)
                delta_global = spectral_field()
                final_delta_list.append(delta_global)

            final_delta = torch.stack(final_delta_list, dim=0)  # [B, C, D, H, W]

            # Apply ROI gate
            if roi_mask is not None:
                final_delta = final_delta * roi_mask

            # Clip to epsilon
            final_delta = final_delta.clamp(-eps, eps)

        nb.commit_batch(keys_list, final_delta.detach().cpu())

        delta_linf = float(final_delta.detach().abs().max().cpu())
        return {
            "noise_loss": float(last_loss.cpu()),
            "delta_linf": delta_linf,
        }